### ISSUE TITLE
SolrRepository

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles#32]
An implementation of `Repository` interface that indexes the crawled pages into an Apache SOLR remote core.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly.

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil the repository's name must match the format ``owner.github.io`` or it must have a project website on branch ``gh-pages``

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/d06c1373-865e-48ad-97a4-1cccf6f08821.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by charlesmike** [comment]
> @charlesmike hi

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike online?

**Comment by charlesmike** [comment]
> @charlesmike online?

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
good

**Comment by amihaiemil** [comment]
@charlesmike pls index

**Comment by charlesmike** [comment]
> @charlesmike pls index

@amihaiemil the repository's name must match the format ``owner.github.io`` or it must have a project website on branch ``gh-pages``

**Comment by amihaiemil** [comment]
@charlesmike index pls

**Comment by amihaiemil** [comment]
This is outscoped - to specific for this project.
