### ISSUE TITLE
LiveWebPage getUrl should return actual url from the address bar

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles#44]
This is because if the site domain has aliasses/cnames, graph crawling won't work.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Index site action started. I'll let you know of the progress...

**Comment by charlesmike** [comment]
> @charlesmike index

@@amihaiemil the repository's name must match the format ``owner.github.io`` or it must have a project website on branch ``gh-pages``

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Index command executed successfully! 
 Add the following script to the website in order to make the search functionality available:

 &lt;script src=&quot;#&quot;&gt;charles&lt;/script&gt; 

 See [logs](http://localhost:8080/charles/api/logs/93f9be8a-c145-474f-ace3-550df20aab42.log) for more details. 
 If you notice any inexplicable errors, please open an issue <a href="https://github.com/amihaiemil/charles-github-ejb">here</a>

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Index site action started. I'll let you know of the progress...

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil the repository's name must match the format ``owner.github.io`` or it must have a project website on branch ``gh-pages``

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by charlesmike** [comment]
> > @charlesmike index

@amihaiemil the repository's name must match the format ``owner.github.io`` or it must have a project website on branch ``gh-pages``

@charlesmike sorry, I do not understand you. See [this link](#) for more details.

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by charlesmike** [comment]
> @charlesmike hi

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Index site action started. I'll let you know of the progress...

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil the repository's name must match the format ``owner.github.io`` or it must have a project website on branch ``gh-pages``

**Comment by amihaiemil** [comment]
done
