### ISSUE TITLE
Redesign ElasticSearchRepository.java

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles#58]
ElasticSearchRepository uses apache http client directly and it's turned out to be big and twisted. Better use [jcabi-http](https://www.github.com/jcabi/jcabi-http), which is a convenience wrapper over it, instead

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
done
